/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrsRouteImport } from './routes/prs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as PlansIndexRouteImport } from './routes/plans/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as WorkoutSelectDayRouteImport } from './routes/workout/select-day'
import { Route as WorkoutActiveRouteImport } from './routes/workout/active'
import { Route as ProgressExerciseIdRouteImport } from './routes/progress.$exerciseId'
import { Route as PlansNewRouteImport } from './routes/plans/new'
import { Route as PlansPlanIdIndexRouteImport } from './routes/plans/$planId/index'
import { Route as WorkoutSummarySessionIdRouteImport } from './routes/workout/summary.$sessionId'
import { Route as PlansPlanIdDayDayIdRouteImport } from './routes/plans/$planId/day/$dayId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrsRoute = PrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansIndexRoute = PlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSelectDayRoute = WorkoutSelectDayRouteImport.update({
  id: '/workout/select-day',
  path: '/workout/select-day',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutActiveRoute = WorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressExerciseIdRoute = ProgressExerciseIdRouteImport.update({
  id: '/progress/$exerciseId',
  path: '/progress/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansNewRoute = PlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdIndexRoute = PlansPlanIdIndexRouteImport.update({
  id: '/plans/$planId/',
  path: '/plans/$planId/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutSummarySessionIdRoute = WorkoutSummarySessionIdRouteImport.update({
  id: '/workout/summary/$sessionId',
  path: '/workout/summary/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanIdDayDayIdRoute = PlansPlanIdDayDayIdRouteImport.update({
  id: '/plans/$planId/day/$dayId',
  path: '/plans/$planId/day/$dayId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prs': typeof PrsRoute
  '/register': typeof RegisterRoute
  '/stats': typeof StatsRoute
  '/plans/new': typeof PlansNewRoute
  '/progress/$exerciseId': typeof ProgressExerciseIdRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/select-day': typeof WorkoutSelectDayRoute
  '/exercises': typeof ExercisesIndexRoute
  '/plans': typeof PlansIndexRoute
  '/workout': typeof WorkoutIndexRoute
  '/workout/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/plans/$planId': typeof PlansPlanIdIndexRoute
  '/plans/$planId/day/$dayId': typeof PlansPlanIdDayDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prs': typeof PrsRoute
  '/register': typeof RegisterRoute
  '/stats': typeof StatsRoute
  '/plans/new': typeof PlansNewRoute
  '/progress/$exerciseId': typeof ProgressExerciseIdRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/select-day': typeof WorkoutSelectDayRoute
  '/exercises': typeof ExercisesIndexRoute
  '/plans': typeof PlansIndexRoute
  '/workout': typeof WorkoutIndexRoute
  '/workout/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/plans/$planId': typeof PlansPlanIdIndexRoute
  '/plans/$planId/day/$dayId': typeof PlansPlanIdDayDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/prs': typeof PrsRoute
  '/register': typeof RegisterRoute
  '/stats': typeof StatsRoute
  '/plans/new': typeof PlansNewRoute
  '/progress/$exerciseId': typeof ProgressExerciseIdRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/workout/select-day': typeof WorkoutSelectDayRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/plans/': typeof PlansIndexRoute
  '/workout/': typeof WorkoutIndexRoute
  '/workout/summary/$sessionId': typeof WorkoutSummarySessionIdRoute
  '/plans/$planId/': typeof PlansPlanIdIndexRoute
  '/plans/$planId/day/$dayId': typeof PlansPlanIdDayDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/prs'
    | '/register'
    | '/stats'
    | '/plans/new'
    | '/progress/$exerciseId'
    | '/workout/active'
    | '/workout/select-day'
    | '/exercises'
    | '/plans'
    | '/workout'
    | '/workout/summary/$sessionId'
    | '/plans/$planId'
    | '/plans/$planId/day/$dayId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/prs'
    | '/register'
    | '/stats'
    | '/plans/new'
    | '/progress/$exerciseId'
    | '/workout/active'
    | '/workout/select-day'
    | '/exercises'
    | '/plans'
    | '/workout'
    | '/workout/summary/$sessionId'
    | '/plans/$planId'
    | '/plans/$planId/day/$dayId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/prs'
    | '/register'
    | '/stats'
    | '/plans/new'
    | '/progress/$exerciseId'
    | '/workout/active'
    | '/workout/select-day'
    | '/exercises/'
    | '/plans/'
    | '/workout/'
    | '/workout/summary/$sessionId'
    | '/plans/$planId/'
    | '/plans/$planId/day/$dayId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  PrsRoute: typeof PrsRoute
  RegisterRoute: typeof RegisterRoute
  StatsRoute: typeof StatsRoute
  PlansNewRoute: typeof PlansNewRoute
  ProgressExerciseIdRoute: typeof ProgressExerciseIdRoute
  WorkoutActiveRoute: typeof WorkoutActiveRoute
  WorkoutSelectDayRoute: typeof WorkoutSelectDayRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  PlansIndexRoute: typeof PlansIndexRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
  WorkoutSummarySessionIdRoute: typeof WorkoutSummarySessionIdRoute
  PlansPlanIdIndexRoute: typeof PlansPlanIdIndexRoute
  PlansPlanIdDayDayIdRoute: typeof PlansPlanIdDayDayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prs': {
      id: '/prs'
      path: '/prs'
      fullPath: '/prs'
      preLoaderRoute: typeof PrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/': {
      id: '/plans/'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/select-day': {
      id: '/workout/select-day'
      path: '/workout/select-day'
      fullPath: '/workout/select-day'
      preLoaderRoute: typeof WorkoutSelectDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/active': {
      id: '/workout/active'
      path: '/workout/active'
      fullPath: '/workout/active'
      preLoaderRoute: typeof WorkoutActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/$exerciseId': {
      id: '/progress/$exerciseId'
      path: '/progress/$exerciseId'
      fullPath: '/progress/$exerciseId'
      preLoaderRoute: typeof ProgressExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/new': {
      id: '/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof PlansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId/': {
      id: '/plans/$planId/'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof PlansPlanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/summary/$sessionId': {
      id: '/workout/summary/$sessionId'
      path: '/workout/summary/$sessionId'
      fullPath: '/workout/summary/$sessionId'
      preLoaderRoute: typeof WorkoutSummarySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planId/day/$dayId': {
      id: '/plans/$planId/day/$dayId'
      path: '/plans/$planId/day/$dayId'
      fullPath: '/plans/$planId/day/$dayId'
      preLoaderRoute: typeof PlansPlanIdDayDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  PrsRoute: PrsRoute,
  RegisterRoute: RegisterRoute,
  StatsRoute: StatsRoute,
  PlansNewRoute: PlansNewRoute,
  ProgressExerciseIdRoute: ProgressExerciseIdRoute,
  WorkoutActiveRoute: WorkoutActiveRoute,
  WorkoutSelectDayRoute: WorkoutSelectDayRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  PlansIndexRoute: PlansIndexRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
  WorkoutSummarySessionIdRoute: WorkoutSummarySessionIdRoute,
  PlansPlanIdIndexRoute: PlansPlanIdIndexRoute,
  PlansPlanIdDayDayIdRoute: PlansPlanIdDayDayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
